<%@ Page Title="" Language="C#" MasterPageFile="~/Master/CWC.Master" AutoEventWireup="true" CodeBehind="paymentReport.aspx.cs" Inherits="CWC_FurnitureSystem.Order.offline.paymentReport" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="css/styleOffline.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">

        function printdiv()
        {
        var headstr = "<html><head><title></title></head><body>";
        var footstr = "</body>";
        var newstr = document.all.item('print').innerHTML;
        var oldstr = document.body.innerHTML;
        document.body.innerHTML = headstr+newstr+footstr;
        window.print();
        document.body.innerHTML = oldstr;
        return false;
        }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <div class="addOfflineContent">
    <div>
        <b>Sales Date:</b> <asp:TextBox ID="txtFrom" runat="server" TextMode="Month" Columns="10"></asp:TextBox>
                    <%--<cc1:CalendarExtender ID="CalendarExtender1" Format="dd/MM/yyyy" runat="server" TargetControlID="txtFrom"></cc1:CalendarExtender>
        --%>
        <asp:Button ID="btnGenerate" runat="server" Text="Generate Report" OnClick="btnGenerate_Click"/>       
    </div>
        <div id="print">
    <div class="top">
        <hr/>
        <h1 style="text-align:center">Payment Transaction Report For: <asp:Label ID="date" runat="server"></asp:Label></h1>
        <table style="width: 100%;">
            <tr>
                <td><b>Company:</b> <asp:Label ID="lblId" runat="server" Text="CWC Furniture Sdn Bhd"></asp:Label></td>
                <td><b>Date Generated:</b> <asp:Label ID="lblDate" runat="server" Text="11/11/2015"></asp:Label></td>
                <td><b>Generated By:</b> <asp:Label ID="lblCust" runat="server" Text="supervisor1"></asp:Label>
                </td>
            </tr>
            
       </table>
        
        <hr/>
    </div>
            
    <div class="addOfflineMainContent">
        
    <div id="tableMain">
    
   <asp:GridView ID="GridView1" AutoGenerateColumns="false" Width="100%" runat="server" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Horizontal" ShowFooter="True">
       <AlternatingRowStyle BackColor="#F7F7F7" />
       <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
       <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" HorizontalAlign="Left" />
       <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
       <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
       <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
       <SortedAscendingCellStyle BackColor="#F4F4FD" />
       <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
       <SortedDescendingCellStyle BackColor="#D8D8F0" />
       <SortedDescendingHeaderStyle BackColor="#3E3277" />
       <Columns>
           
       <asp:TemplateField HeaderText = "No" ItemStyle-Width="40">
            <ItemTemplate>
                <asp:Label ID="lblRowNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
            </ItemTemplate>

        <ItemStyle Width="40px"></ItemStyle>
       </asp:TemplateField>
           <asp:BoundField DataField="paymentId" DataFormatString="A{0:0000}" HeaderText="Payment ID" SortExpression="paymentId" />
           <asp:BoundField DataField="paymentDate" HeaderText="Payment Date" DataFormatString="{0:d}" SortExpression="paymentDate" />
           <asp:BoundField DataField="paymentType" HeaderText="Payment Type" SortExpression="paymentType" />
           <asp:BoundField DataField="customer" HeaderText="Paid By" SortExpression="customer" />
           <asp:BoundField DataField="paymentAmount"  ItemStyle-HorizontalAlign="Right" HeaderStyle-HorizontalAlign="Right" DataFormatString="{0:#.00}" HeaderText="Amount(RM)" SortExpression="paymentAmount" />
        </Columns>
       </asp:GridView>

        </div>

    </div>
    </div>
    
    </div>
    <div id="buttonGroup">
        <asp:Button ID="btnPrint" Text="Print Report" runat="server" OnClientClick="printdiv()"/>
    </div>
</asp:Content>
